"use client";

import { useState } from "react";
import { Expand, X } from "lucide-react";
import type { VisualDiagramConfig } from "./schema";

export function VisualDiagramClient({ title, imageUrl, alt, caption, kind, legend }: VisualDiagramConfig) {
  const [open, setOpen] = useState(false);
  return <><figure className="not-prose my-8 overflow-hidden rounded-2xl border border-border bg-card text-card-foreground shadow-sm"><figcaption className="border-b border-border bg-muted/35 px-5 py-4 sm:px-6"><p className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">{kind === "whiteboard" ? "Whiteboard" : kind === "system" ? "System diagram" : "Concept diagram"}</p><h3 className="mt-1 text-lg font-semibold tracking-tight text-foreground">{title}</h3></figcaption><div className="group relative bg-muted/20"><img src={imageUrl} alt={alt} className="block max-h-[40rem] w-full object-contain" loading="lazy" /><button type="button" onClick={() => setOpen(true)} className="absolute right-3 top-3 inline-flex items-center gap-2 rounded-md border border-border bg-card/95 px-3 py-2 text-xs font-medium text-foreground shadow-sm hover:bg-muted"><Expand className="size-3.5" /> Expand</button></div>{(caption || legend?.length) ? <div className="space-y-3 border-t border-border px-5 py-4 sm:px-6">{caption ? <p className="text-sm leading-relaxed text-muted-foreground">{caption}</p> : null}{legend?.length ? <ul className="flex flex-wrap gap-2">{legend.map((item) => <li key={item} className="rounded-full border border-border bg-muted px-2.5 py-1 text-xs text-muted-foreground">{item}</li>)}</ul> : null}</div> : null}</figure>{open ? <div className="fixed inset-0 z-[100] flex items-center justify-center bg-foreground/70 p-4" role="dialog" aria-modal="true" aria-label={title}><div className="relative max-h-full max-w-6xl overflow-auto rounded-xl bg-card p-3 shadow-2xl"><button type="button" onClick={() => setOpen(false)} className="absolute right-5 top-5 rounded-md border border-border bg-card p-2 text-foreground" aria-label="Close expanded diagram"><X className="size-4" /></button><img src={imageUrl} alt={alt} className="block max-h-[85vh] w-auto max-w-full" /></div></div> : null}</>;
}
