ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'VISUAL_WALKTHROUGH';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'VISUAL_DIAGRAM';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'ROADMAP';
